In [1]:
import pandas as pd
import numpy as np
import re
import string

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn import metrics

# 1. Preprocessing
def simple_preprocess(text):
    text = text.lower()
    text = re.sub(r"\n", " ", text)
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)
    return text

# 2. Load data
df = pd.read_csv("/content/df_file.csv")
df["Text"] = df["Text"].astype(str).apply(simple_preprocess)

# 3. Ambil fitur dan label
X = df["Text"]
y = df["Label"]

# 4. Split data (train 75%, test 25%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 5. Pipeline model
model = make_pipeline(TfidfVectorizer(), MultinomialNB())

# 6. Latih model
model.fit(X_train, y_train)

# 7. Prediksi dan evaluasi
y_pred = model.predict(X_test)

# 8. Tampilkan hasil evaluasi
print(f"Akurasi: {metrics.accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(metrics.classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

Akurasi: 0.9354

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       112
           1       0.93      1.00      0.97       128
           2       0.94      0.93      0.93        95
           3       0.97      0.81      0.88        94
           4       0.92      0.97      0.94       128

    accuracy                           0.94       557
   macro avg       0.94      0.93      0.93       557
weighted avg       0.94      0.94      0.93       557

Confusion Matrix:
[[105   2   1   0   4]
 [  0 128   0   0   0]
 [  1   1  88   2   3]
 [  6   6   2  76   4]
 [  1   0   3   0 124]]
